version: "3.8"

services:
  frontend:
    build:
      context: ./frontend
      args:
        VITE_API_BASE_URL: "http://localhost:8000"
    ports:
      - "8080:80"
    volumes:
      - frontend_node_modules:/app/node_modules

  db:
    image: postgres:15
    environment:
      POSTGRES_USER: user
      POSTGRES_PASSWORD: password
      POSTGRES_DB: appdb
    ports:
      - "5432:5432"
    volumes:
      - db_data:/var/lib/postgresql/data

volumes:
  db_data:
  frontend_node_modules:
