version: "3.8"

services:
  backend:
    build: ./backend
    ports:
      - "8000:8000"
    depends_on:
      - db
    environment:
      DATABASE_URL: postgres://user:password@db:5432/appdb
      SECRET_KEY: FJV)(*FH)N)@#C*#_)$VC#$*)CV#$)J
      ZYMBIT_CONNECNTED: "false"
      CORS_ALLOWED_ORIGINS: "http://localhost:8080"

  frontend:
    build:
      context: ./frontend
      args:
        VITE_API_BASE_URL: "http://localhost:8000"
    ports:
      - "8080:80"
    depends_on:
      - backend
    volumes:
      - frontend_node_modules:/app/node_modules

  db:
    image: postgres:15
    environment:
      POSTGRES_USER: user
      POSTGRES_PASSWORD: password
      POSTGRES_DB: appdb
    ports:
      - "5432:5432"
    volumes:
      - db_data:/var/lib/postgresql/data

volumes:
  db_data:
  frontend_node_modules:
